apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  push:
    branches:
      - "**"
jobs:
  build:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world"
  Jobonly:
    steps:
      - name: Container Test
        run: echo "Good Bye"
        uses: docker://alpine:3.19
        shell: sh
