apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  push:
    branches:
      - "**"
jobs:
  build:
    steps:
      - uses: AutoTest.PublishEvidence.02103975-739c-40c3-b0fe-a8d29dbedcff.Action
  container:
    steps:
      - name: container test
        run: echo "Hello from Alpinetest "
        uses: docker://alpine:3.19
        shell: sh
