apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  push:
    branches:
      - "**"
jobs:
  build:
    steps:
      - name: Say hello
        run: |
          echo "hello world"
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
      - with:
          content: This is created today for testing functional test
        uses: AutoTest.PublishEvidence.36c54590-907d-4c00-b1d8-02c6ed158a5a.Action
