apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  push:
    branches:
      - "**"
jobs:
  build:
    steps:
      - name: Say hello
        run: |
          echo "hello world"
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
      - with:
          content: This is created today for testing functional test
        uses: AutoTest.PublishEvidence.9f1b6b62-595a-4a2c-83ce-a8c64a1f8d1f.Action
