apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  push:
    branches:
      - "**"
jobs:
  build:
    steps:
      - name: Say hello
        run: |
          echo "hello world"
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
      - with:
          content: This is created today for testing functional test
        uses: AutoTest.PublishEvidence.76cf001b-6bb2-4ff6-8fa8-7bf825c162f8.Action
